config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users, except: :index
  resources :envelopes, except: [:edit, :delete] do
    resources :parchments, only: [:create, :destroy]
  end
  get 'zipfile', to: 'zipfile#download', as: 'zipfile_download'
    get 'download', to: 'download#download_single'

  get 'sign-in', to: 'sessions#new', as: 'sign-in'
  post 'sign-in', to: 'sessions#create'
  get 'sign-up', to: 'registrations#new', as: 'sign-up'
  post 'sign-up', to: 'registrations#create'
  delete 'sign-out', to: 'sessions#destroy', as: 'sign-out'
  post '/envelopes/:id/parchments', to: 'parchments#create'
  post '/:slug/password', to: 'envelopes#authenticate'
  get '/:token/confirm_email/', to: 'registrations#confirm_email', as: 'confirm_email'
  post '/search', to: 'search#create', as: 'envelope_search'
  get '/:slug', to: 'envelopes#show', as: 'get_slug'
  post '/:slug', to: 'envelopes#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :envelope
end

app/models/envelope.rb
class Envelope < ApplicationRecord
  has_many :parchments
  has_many :archives
  belongs_to :user
  validates :slug, presence: true, uniqueness: true
  accepts_nested_attributes_for :parchments
  has_secure_password  :validations => false

  def to_param
    slug
  end

end

app/models/parchment.rb
class Parchment < ApplicationRecord
  belongs_to :envelope
  delegate :user, to: :envelope
   mount_uploader :file, FileUploader
     # validates :file, file_size: { less_than: 2.bytes }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :envelopes
  has_many :parchments, through: :envelopes
  validates :name, presence: true
  validate :flatiron_email?
  validates :email_address, presence: true, uniqueness: true
  has_secure_password

  def validate_email
    self.email_confirmed = true
    self.confirm_token = nil
  end

  def set_confirmation_token
    if self.confirm_token.nil?
      self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end

  def flatiron_email?
    if !self.email_address.end_with? "@flatironschool.com"
        errors.add :base, "Not a Flatiron email address"
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user, :unauthenticated_only, :authenticated_only

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def unauthenticated_only
    redirect_to root_path, notice: "You're already logged in" if logged_in?
  end

  def authenticated_only
    redirect_to sign_in_path, notice: "You must be logged in to do that" unless logged_in?
  end

end

app/controllers/download_controller.rb
class DownloadController < ApplicationController
  def download_single
  url = (Parchment.find_by_id(params[:parchment_id])).file.url
  data = open(url)
  file_name = Parchment.find_by_id(params[:parchment_id])[:file]
  send_data data.read, filename: file_name
end

end

app/controllers/envelopes_controller.rb
class EnvelopesController < ApplicationController
  before_action :set_s3_direct_post, only: [:edit,:show]
  before_action :authenticated_only, only: [:create, :edit, :update]
  before_action :set_envelope, only: [:show, :edit, :update, :authenticate]

  def new
    @envelope = Envelope.new
    @times = ExpirationSetter.expiration_options
    @user = User.new
  end

  def create
    slug = WordGetter.random_word
    expiration = ExpirationSetter.set_expiration(params[:envelope][:expiration])
    @envelope = Envelope.create(user: current_user, slug: slug, expiration: expiration)
    redirect_to  "/" + @envelope.slug
  end

  def show
    if @envelope == nil
      redirect_to root_path, flash: {error: "That's not a valid envelope"}
    elsif @envelope.password_digest == nil
      session[:envelope_id] = @envelope.id
    elsif @envelope.user == current_user || session[:envelope_id] == @envelope.id
      @parchments = @envelope.parchments
      session[:envelope_id] = nil
      render :show
    else
      render :enterpassword
    end
  end

  def authenticate
    if @envelope.authenticate(params[:password])
      session[:envelope_id] = @envelope.id
      render :show
    else
      render :enterpassword, flash: {error: 'Incorrect password'}
    end
  end

  def index
    @envelopes = current_user.envelopes
  end

  def edit
  end

  def update
    @envelope.password = params[:password]
    @envelope.save
    render :show
  end

  private

  def set_envelope
    @envelope = Envelope.find_by_slug(params[:slug])
  end

  def set_s3_direct_post
    @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/parchments_controller.rb
class ParchmentsController < ApplicationController
  before_action :find_envelope, only: :create

  def create
    params[:attachment][:file].each do |file|
      Parchment.create( envelope_id: @envelope.id, file: file) unless file == ""
    end
    redirect_to "/" + @envelope.slug
  end


  def destroy
    Parchment.find_by_id(params[:id]).destroy
    redirect_to :back
  end


  private

  def find_envelope
    @envelope = Envelope.find_by_slug(params[:envelope_id])
  end


end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :set_user, only: :new

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      user.set_confirmation_token
      user.save(validate: false)
      UserMailer.registration_confirmation(user).deliver_now
      redirect_to sign_in_path, flash: {success: "Confirmation sent to #{user.email_address} Please confirm your email address to continue"}
    else
      render :new
    end
  end

  def confirm_email
    user = User.find_by_confirm_token(params[:token])
    if user
      user.validate_email
      user.save(validate: false)
      session[:user_id] = user.id
      redirect_to user_path(user), flash: {success: "Thanks for confirming your email address!"}
    else
      redirect_to sign_up_path, flash: {error: "Sorry, user doesn't exist"}
    end
  end

  private
  def set_user
    @user = User.new
  end

  def user_params
    params.require(:user).permit(:name, :email_address, :password, :password_confirmation)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def create
    @envelope = Envelope.find_by_slug(params[:slug])
    if @envelope
      redirect_to "/" + @envelope.slug
    else
      redirect_to root_path, flash: {error: 'That is not a valid envelope'}
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :unauthenticated_only, only: [:new, :create]

  def new
  end

  def create
    @user = User.find_by(email_address: params[:email_address])
    if @user.email_confirmed == false
      redirect_to sign_in_path, flash: {error: "Please confirm your email address to continue"}
    elsif @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to sign_in_path, flash: {error: "Username or password incorrect"}
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, flash: {success: "You have successfully logged out"}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    if @user == current_user
      render :show
    else
      redirect_to root_path, flash: {error: 'Sealed by Signet'}
    end
  end
end

app/controllers/zipfile_controller.rb
class ZipfileController < ApplicationController
  def download
    zipped_file = FileZipper.perform(params[:envelope_id])
    send_file zipped_file.archive_file, disposition: 'attachment'
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end
end

app/helpers/download_helper.rb
module DownloadHelper
end

app/views/envelopes/edit.html.erb
<%= render partial: '/parchments/upload_form', locals: {envelope: @envelope} %>

app/views/envelopes/enterpassword.html.erb
<h2>You are attempting to visit a protected envelope. Please enter the password</h2>
<%= form_tag( params[:slug] + "/password", method: "post") do %>
  <%= label_tag(:password, "Password:") %>
    <%= password_field_tag :password , nil, class: 'form-control', placeholder: 'Enter envelope password' %>
  <%= submit_tag "Enter", class: 'btn btn-default' %>
<% end %>

app/views/envelopes/index.html.erb
<h1> Envelopes: </h1>
<% @envelopes.each do |envelope| %>
 
  
  






<div class="row" style= "border-bottom: 3px solid black; margin-bottom:10px;">

  <div class="col-sm-6">
<h1> <strong>Envelope: </strong><%= link_to envelope.slug , "/" + envelope.slug %> </h1>
<h1> <strong>Expires: </strong> <%= envelope.expiration.strftime("%a, %b %-d, %Y, %I:%M %p") %></h1>
  </div>


  <div class="col-sm-6">
<h1> <strong>Parchments:</strong> </h1>

<% envelope.parchments.each do |parchment| %>
<h2> <%= link_to parchment[:file], parchment.file.url%> </h2>

<% end %>
  </div>








</div>

<% end %>

app/views/envelopes/new.html.erb
<%= form_for @envelope do |f| %>
  <h3><%= f.label :expiration, 'Select an Expiration' %></h3><br>
  <%= f.select :expiration, options_for_select(@times), {}, class:'btn btn-default btn-xl dropdown-toggle' %>
  <%= f.submit 'Create Envelope', class: 'btn btn-default' %>
<% end %>

app/views/envelopes/show.html.erb
<div class="row" style= "border-bottom: 3px solid black; margin-bottom:10px;">

  <div class="col-sm-4">
    <h1> <strong>Envelope:</strong> <%= @envelope.slug %> </h1>
    <h1> <strong>Creator:</strong> <%= @envelope.user.name %> </h1>
    <h1> <strong>Expires:</strong> <%= @envelope.expiration.strftime("%a, %b %-d, %Y, %I:%M %p") %></h1>
  </div>


  <div class="col-sm-4">
    <h1> <strong>Parchments:</strong> </h1>
    <% if @envelope.user == current_user %>
    <div id = "counter"><p></p> </div>
      <%= render partial: '/parchments/upload_form', locals: {envelope: @envelope} %>
    <% end %>
    <% @envelope.parchments.each do |parchment| %>
    <h4> <%=  parchment[:file] %> </h4>
      <div class="btn-group">
        <%= link_to "Download", { controller: 'download', action: 'download_single', method: 'get', parchment_id: parchment.id}, class: "btn btn-default" %>
        <% if @envelope.user == current_user %>
        <%= link_to "Delete", [@envelope, parchment], :method => :delete, class: 'btn btn-danger' %>
        <% end %>
      </div>
    <% end %>
    <% if @envelope.parchments.count > 1 %>
    <div class="row" style= "margin-top: 10px;">
      <%= link_to "Download All", { controller: 'zipfile', action: 'download', method: 'get', envelope_id: @envelope.id, disable_with: 'Downloading Zip...' }, class: "btn btn-default center-block" %>
      <br><br>
    </div>
    <% end %>
  </div>


<script type="text/javascript">
$( '#file_input' ).hover(function() {
  $('#counter').html("Added " + $('#file_input')[0].files.length+ " Files")
});
</script>




  <div class="col-sm-4">
    <% if @envelope.user == current_user %>
    <%= form_tag "" do %>
    <%= label_tag :password %>
    <%= password_field_tag :password, nil, placeholder: "Create Password" %><br>
    <%= submit_tag ("Assign Password"), class: "btn btn-default" %>
    <% end %>
    <% end %>

app/views/home/index.html.erb
<div style="background-color:transparent !important" class="jumbotron  vertical-center">
  <h1>Welcome to Signet!</h1>
  <p>Signet is a simple way to send files to others. Log in and create a new envelope, optionally attach a password, and select the files you want to upload and the longevity of the files. The new envelope will consist of the uploaded files and a specific slug that can be used to easily access the files. </p>
</div>



<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
    <%= form_tag('/search', method: 'post') do %>
    <%= text_field_tag :slug, nil, class: 'form-control center-block', placeholder: 'Enter envelope slug' %>
    <%= submit_tag "Find an Envelope", class:'btn btn-default btn-lg center-block'  %><br><br>
    <% end %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class= "col-mid-8">
  <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"> <%= message %>
    <a class="close" data-dismmiss="alert"> &#215; </a>
    </div>
    <% end %>
  </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Signet</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">Signet</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if logged_in? %>
          <li><%= link_to 'Create Envelope', new_envelope_path %></li>
          <li><%= link_to 'My Envelopes', envelopes_path, method: :get %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <% if logged_in? %>

            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Sign Out", sign_out_path, method: "delete" %></li>
            </ul>
            <% else %>
            <li><a href="<%= sign_in_path %>">Sign In</a></li>
            <li><a href="<%= sign_up_path %>">Sign Up</a></li>
            <% end %>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="container">
  <%= flash_messages %>
    <%= yield %>
  </div>
</body>
</html>

app/views/parchments/_upload_form.html.erb
  <%= form_for [@envelope, Parchment.new], :html => {:multipart => true} do |f| %>
  <label class='btn btn-primarybtn-file center-block'>
  <%= f.file_field :file, multiple: true, display: 'none', name: "attachment[file][]", onchange: "validateFiles(this);", data: { max_file_size: 5.megabytes }, id: 'file_input' %>
    </label>
  <%= f.submit "Save Envelope", class: "btn btn-default" %>
  <% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.name %>!</h1>

<h2><strong><%= link_to 'Create a new envelope', new_envelope_path %></strong></h2>

<h2><strong>Envelopes</strong></h2>
  <% if @user.envelopes.count == 0 %>
    <h3>No envelopes yet! Create one and send some stuff!</h3>
  <% end %>
<div class="col-md-4">
  <% @user.envelopes.each do |envelope| %>
  <ul class="list-unstyled">
    <li><h3><%= link_to envelope.slug, "/#{envelope.slug}" %></h3></li>
    <span class="badge"><%= envelope.parchments.count %></span> parchments in this envelope
  </ul>
  <% end %>
</div>